### ISSUE TITLE
Failed to update stringi to 1.4.5

### ISSUE THREAD

**Issue by PauloRCF23** [gagolews/stringi#373] opened 2020-02-10 11:46 UTC
Hi,
I'm trying to update stringi from 1.4.4 to 1.4.5 in Windows 10 64 bits with R 3.6.2 and always get error messages. Below is an example:

Registered S3 methods overwritten by 'lme4':
  method                          from
  cooks.distance.influence.merMod car 
  influence.merMod                car 
  dfbeta.influence.merMod         car 
  dfbetas.influence.merMod        car 
lattice theme set by effectsTheme()
See ?effectsTheme for details.
The Commander GUI is launched only in interactive sessions
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/prcf/Documents/R/win-library/3.6/stringi'
* restoring previous 'C:/Users/prcf/Documents/R/win-library/3.6/stringi'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\prcf\Documents\R\win-library\3.6\00LOCK-stringi\stringi\libs\icudt61l.dat to C:\Users\prcf\Documents\R\win-library\3.6\stringi\libs\icudt61l.dat: Invalid argument
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\prcf\Documents\R\win-library\3.6\00LOCK-stringi\stringi\libs\x64\stringi.dll to C:\Users\prcf\Documents\R\win-library\3.6\stringi\libs\x64\stringi.dll: Permission denied
Warning in install.packages :
  installation of package 'stringi' had non-zero exit status

I also tried to delete the packages stringi and stringr from win-library and install from scratch, but with the same result. The error occurs both in R and RStudio.
I have RTools installed.
Thanks for any assistance.

**Comment by gagolews** [comment] 2020-02-11 03:24
Thanks, I am aware of than, the problem is on the CRAN side, it should be fixed once I submit another package update, hopefully in a week

**Closed by gagolews** 2020-02-11 03:24 UTC

**Comment by PauloRCF23** [comment] 2020-02-11 15:20
Thanks for the feedback.

**Comment by gagolews** [comment] 2020-02-19 04:12
fixed now.

**Comment by PauloRCF23** [comment] 2020-02-19 09:51
Well done!
Worked like a charm.
Thanks
