### ISSUE TITLE
Compilation Failure on CentOS

### ISSUE THREAD

**Issue by jeffPHE** [gagolews/stringi#300] opened 2018-05-09 18:25 UTC
I cannot install stringi under CentoOS. I've tried multiple R versions, I've tried installing from CRAN both with and without disabling the pkg-config as well as getting the latest version from github and always get the same error:

`In file included from icu61/i18n/number_types.h:14:0,
                 from icu61/i18n/number_affixutils.h:11,
                 from icu61/i18n/number_affixutils.cpp:8:
icu61/unicode/numberformatter.h:688:21: error: 'icu_61::number::Notation::Notation' names constructor
icu61/unicode/numberformatter.h:1072:20: error: 'icu_61::number::Rounder::Rounder' names constructor
icu61/unicode/numberformatter.h:1110:20: error: 'icu_61::number::Rounder::Rounder' names constructor
icu61/unicode/numberformatter.h:1146:20: error: 'icu_61::number::Rounder::Rounder' names constructor
make: *** [icu61/i18n/number_affixutils.o] Error 1
ERROR: compilation failed for package 'stringi'
`

**Comment by gagolews** [comment] 2018-05-09 20:33
duplicate of #296

**Closed by gagolews** 2018-05-09 20:34 UTC
