### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by mizraelson** [gagolews/stringi#456] opened 2021-09-11 19:34 UTC
Installation fails.

```
> install.packages("stringi")
Installing package into ‘/home/mizraelson/.lib/R/library’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Secure CRAN mirrors

 1: 0-Cloud [https]
 2: Australia (Canberra) [https]
 3: Australia (Melbourne 1) [https]
 4: Australia (Melbourne 2) [https]
 5: Australia (Perth) [https]
 6: Austria [https]
 7: Belgium (Brussels) [https]
 8: Brazil (BA) [https]
 9: Brazil (PR) [https]
10: Brazil (RJ) [https]
11: Brazil (SP 1) [https]
12: Brazil (SP 2) [https]
13: Bulgaria [https]
14: Canada (MB) [https]
15: Canada (ON 2) [https]
16: Chile (Santiago) [https]
17: China (Beijing 2) [https]
18: China (Hefei) [https]
19: China (Hong Kong) [https]
20: China (Guangzhou) [https]
21: China (Lanzhou) [https]
22: China (Nanjing) [https]
23: China (Shanghai 1) [https]
24: China (Shanghai 2) [https]
25: China (Shenzhen) [https]
26: Costa Rica [https]
27: Cyprus [https]
28: Czech Republic [https]
29: Denmark [https]
30: East Asia [https]
31: Ecuador (Cuenca) [https]
32: Ecuador (Quito) [https]
33: Estonia [https]
34: France (Lyon 1) [https]
35: France (Lyon 2) [https]
36: France (Marseille) [https]
37: France (Montpellier) [https]
38: France (Paris 1) [https]
39: Germany (Erlangen) [https]
40: Germany (Leipzig) [https]
41: Germany (Göttingen) [https]
42: Germany (Münster) [https]
43: Germany (Regensburg) [https]
44: Greece [https]
45: Hungary [https]
46: Iceland [https]
47: India [https]
48: Indonesia (Jakarta) [https]
49: Iran [https]
50: Italy (Milano) [https]
51: Italy (Padua) [https]
52: Japan (Tokyo) [https]
53: Korea (Gyeongsan-si) [https]
54: Korea (Seoul 1) [https]
55: Korea (Ulsan) [https]
56: Malaysia [https]
57: Mexico (Mexico City) [https]
58: Mexico (Texcoco) [https]
59: Morocco [https]
60: Netherlands [https]
61: New Zealand [https]
62: Norway [https]
63: Russia (Moscow) [https]
64: South Africa (Johannesburg) [https]
65: Spain (A Coruña) [https]
66: Spain (Madrid) [https]
67: Sweden (Borås) [https]
68: Sweden (Umeå) [https]
69: Switzerland [https]
70: Taiwan (Taipei) [https]
71: Turkey (Denizli) [https]
72: Turkey (Istanbul) [https]
73: Turkey (Mersin) [https]
74: UK (Bristol) [https]
75: UK (London 1) [https]
76: USA (IA) [https]
77: USA (KS) [https]
78: USA (MI) [https]
79: USA (OH) [https]
80: USA (OR) [https]
81: USA (TN) [https]
82: USA (TX 1) [https]
83: Uruguay [https]
84: (other mirrors)

Selection: 80
trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/stringi_1.7.4.tar.gz'
Content type 'application/x-gzip' length 7599762 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /home/mizraelson/miniconda3/lib/R
checking for R... /home/mizraelson/miniconda3/lib/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu69/data
checking for x86_64-conda-linux-gnu-gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/mizraelson/miniconda3/bin/x86_64-conda-linux-gnu-cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... no
*** Trying with C++11 compiler disabled.
checking for local ICUDT_DIR... icu55/data
checking for x86_64-conda-linux-gnu-gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/mizraelson/miniconda3/bin/x86_64-conda-linux-gnu-cpp
checking for grep that handles long lines and -e... (cached) /bin/grep
checking for egrep... (cached) /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for elf.h... (cached) yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++14 accepts -g... yes
checking whether the C++ compiler supports the long long type... no

*** *********************************************************************
*** stringi cannot be built with these settings in place.
*** See the INSTALL file for the solutions to the most common problems.
*** Moreover, explore the list of open and closed issues at
*** https://github.com/gagolews/stringi/issues/
*** *********************************************************************

ERROR: configuration failed for package ‘stringi’
* removing ‘/home/mizraelson/.lib/R/library/stringi’

The downloaded source packages are in
	‘/tmp/RtmpBPfWE9/downloaded_packages’
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status
```

```
R --version
R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
```

```
x86_64-conda-linux-gnu-c++ -v
Reading specs from /home/mizraelson/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/specs
COLLECT_GCC=x86_64-conda-linux-gnu-c++
COLLECT_LTO_WRAPPER=/home/mizraelson/miniconda3/bin/../libexec/gcc/x86_64-conda-linux-gnu/9.3.0/lto-wrapper
Target: x86_64-conda-linux-gnu
Configured with: /home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/src/gcc/configure --build=x86_64-build_pc-linux-gnu --host=x86_64-build_pc-linux-gnu --target=x86_64-conda-linux-gnu --prefix=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/gcc_built --with-sysroot=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/gcc_built/x86_64-conda-linux-gnu/sysroot --enable-languages=c,c++,fortran,objc,obj-c++ --with-pkgversion='crosstool-NG 1.24.0.133_b0863d8_dirty' --enable-__cxa_atexit --disable-libmudflap --enable-libgomp --disable-libssp --enable-libquadmath --enable-libquadmath-support --enable-libsanitizer --enable-libmpx --with-gmp=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/buildtools --with-mpfr=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/buildtools --with-mpc=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/buildtools --with-isl=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/.build/x86_64-conda-linux-gnu/buildtools --enable-lto --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --enable-threads=posix --enable-target-optspace --enable-plugin --enable-gold --disable-nls --disable-multilib --with-local-prefix=/home/builder/ktietz/cos6/ci_cos6/ctng-compilers_1622658800915/work/gcc_built/x86_64-conda-linux-gnu/sysroot --enable-long-long --enable-default-pie
Thread model: posix
gcc version 9.3.0 (crosstool-NG 1.24.0.133_b0863d8_dirty)
```

**Comment by gagolews** [comment] 2021-09-12 07:11
Duplicate of  #452

**Closed by gagolews** 2021-09-12 07:11 UTC
