### ISSUE TITLE
1.6.2 Windows binary on CRAN?

### ISSUE THREAD

**Issue by slodge** [gagolews/stringi#440] opened 2021-06-10 16:08 UTC
We're seeing very slow tidyverse install times on Windows at present because https://cran.r-project.org/src/contrib/ contains 1.6.2 but https://cran.r-project.org/bin/windows/contrib/4.1/ only contains 1.6.1

Is this deliberate? if not, is there an easy way to update it?

Apologies if this is already covered elsewhere - I looked on https://github.com/gagolews/stringi/releases/tag/v1.6.2 and on https://cran.r-project.org/web/packages/stringi/ and couldn't spot anything (there are develop binaries for 1.6.2 listed on CRAN)

**Comment by gagolews** [comment] 2021-06-10 23:28
duplicate of #436

**Comment by slodge** [comment] 2021-06-11 06:09
Sorry - I have no idea how I didn't spot the other issue!

With this level of detail, I think I'll go back and check the code I wrote
yesterday... Thanks for pointing me the right way :+1:

**Comment by gagolews** [comment] 2021-06-11 06:55
No worries.

I guess I should write my 3rd email to the CRAN team with regards to the above...

**Comment by gagolews** [comment] 2021-08-05 04:48
Now on CRAN.

**Closed by gagolews** 2021-08-05 04:48 UTC
