### ISSUE TITLE
Sub-optimal vectorisation in str_sub<-

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#234] opened 2016-10-13 01:18 UTC
```R
library(stringi)
x <- "abcdefgh"
str_sub(x, c(1, 3), c(1, 3))  <- c("X", "Y")
x
#> [1] "Xbcdefgh" "abYdefgh"
```

Ideally it would return `"XbYdefgh"`

**Comment by gagolews** [comment] 2016-10-20 17:12
Duplicate of #30

**Closed by gagolews** 2016-10-20 17:12 UTC
