### ISSUE TITLE
Stringi with ICU on cran.r-project.org repo

### ISSUE THREAD

**Issue by kolbeinnj** [gagolews/stringi#316] opened 2018-07-09 17:42 UTC
This is more a question or feature request.

We are using R on research network without internet access and have our local cran mirror. The problem with stringi on mirrored repo is the fact there are need for internet access for the ICU part. As a workaround we do download stringi-master.zip from https://github.com/gagolews/stringi and make it available for R users on the closed network. But the drawback is the inconvenience when R is updated to new version as a part of OS update, stringi package often need update and then we need to download newer version from github, so this gets more complicated for both users and admins.

Perhaps there is reason for not having ICU available with the cran package and we need then to live with our current situation.

For your information, here are the errors we get when we try to install stringi from our mirror.

`install.packages('ggplot2',repos=https://cran.decode.is')

*** ICU4C 50.1.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 52, are not met
*** Trying with "standard" fallback flags
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** The available ICU4C cannot be used
checking whether we may compile src/icu61/common/putil.cpp... yes
checking whether we can fetch icudt... downloading the ICU data library (icudt)
output path: icu61/data/icudt61l.zip
trying URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt61l.zip'

trying URL 'http://www.gagolewski.com/software/stringi/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.gagolewski.com/software/stringi/icudt61l.zip'

trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'

trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip'

trying URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'

trying URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip'

icudt download failed
Error: Stopping on error`

**Comment by gagolews** [comment] 2018-07-10 08:13
Yup, "everything happens for a reason" :)

Duplicate of #311, #290, #282, #225, and a few others

**Closed by gagolews** 2018-07-10 08:13 UTC
