### ISSUE TITLE
The tip information when install the stringi: stringi cannot be built with these settings in place.

### ISSUE THREAD

**Issue by honghh2018** [gagolews/stringi#479] opened 2022-06-15 01:54 UTC
Hi @jeroen , @All
        I install the stringi in conda environment, but it get me the below error:
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for elf.h... (cached) yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++14 accepts -g... yes
checking whether the C++ compiler supports the long long type... no

*** *********************************************************************
*** stringi cannot be built with these settings in place.
*** See the INSTALL file for the solutions to the most common problems.
*** Moreover, explore the list of open and closed issues at
*** https://github.com/gagolews/stringi/issues/
*** *********************************************************************

my system was Centos7, x86_64.
# R.version
> R.version
               _                           
platform       x86_64-conda-linux-gnu      
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up 

Had any advices for this issue?
Best
hanhuihong

**Comment by gagolews** [comment] 2022-06-17 06:32
Have you looked at #296, #472, #461, etc.?

**Comment by gagolews** [comment] 2022-06-28 06:49
Duplicate of #481 - see the fix therein.

**Closed by gagolews** 2022-06-28 06:49 UTC
