### ISSUE TITLE
Windows binaries cannot be compiled on CRAN

### ISSUE THREAD

**Issue by pgiraudoux** [gagolews/stringi#328] opened 2018-09-15 15:32 UTC
It makes some months that stringi 1.2.4 cannot be compiled for windows on CRAN , see error: https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/stringi-00check.html
A a result, on R package update one gets:

 > update.packages(ask='graphics',checkBuilt=TRUE)

   There are binary versions available but the source versions are later:
         binary source needs_compilation
stringi  1.1.7  1.2.4              TRUE

Do you want to install from sources the packages which need compilation?
y/n:

Which re-install the same version at each update...

Please can you fix this ?
Best,

**Comment by mrchypark** [comment] 2018-09-17 14:41
same issue.

**Comment by yutannihilation** [comment] 2018-09-17 14:52
You can try this:

``` r
install.packages(
    "https://github.com/gagolews/stringi/raw/master/devel/winbuilder/3.5/stringi_1.2.4.zip",
    repos = NULL,
)
```

c.f. https://github.com/gagolews/stringi/issues/304#issuecomment-421878738

**Comment by mrchypark** [comment] 2018-09-17 15:01
@yutannihilation many thx! but still issue. what's wrong with this issue? rtools unstables now?

**Comment by pgiraudoux** [comment] 2018-09-17 16:30
Thanks @yutannihilation  for the workaround. 

The issue stays on CRAN now. For some reasons the check of version 1.2.4 does not go through for windows, stays on error, and users downloading binaries from CRAN are stuck since months. Packages on CRAN are not expected to be downloaded safely from elsewhere.

Best,

Patrick

**Comment by gagolews** [comment] 2018-09-18 10:40
duplicate of #320, see also #313

**Closed by gagolews** 2018-09-18 10:40 UTC
