### ISSUE TITLE
Problems installing on Ubuntu 20.04 (anaconda/miniconda) x86_64-conda-linux-gnu-c++ -std=gnu++11: checking whether the C++ compiler supports the long long type... no

### ISSUE THREAD

**Issue by naglemi** [gagolews/stringi#461] opened 2021-11-05 22:04 UTC
Hello,

Firstly, thank you to the developers and community for all your work on producing and advancing the stringi package! I've long relied on `stringi` as a dependency for `stringr`, which I've found essential for my data parsing workflows.

I'm trying to install on a new machine with Ubuntu 20.04, with R version 3.6.3. I was able to install with no problem with the same R version on Ubuntu 18.04 and CentOS 7. I'm running a default installation of Ubuntu 20.04.

Sorry for not having done more troubleshooting on my end, but the cause of the failed installation is very unclear to me and I don't know where to begin. It may involve a dependency with the default C++ compiler in Ubuntu 20.04 and support in this compiler for the "long long" data structure. Please see the output below. Thanks for taking a look!

Worth noting, I'm able to install and run other R packages (e.g. `Rcpp`) without problems.

```
> install.packages("stringi")
trying URL 'https://cloud.r-project.org/src/contrib/stringi_1.7.5.tar.gz'
Content type 'application/x-gzip' length 7600378 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /home/michael/anaconda3/envs/gmolabeler/lib/R
checking for R... /home/michael/anaconda3/envs/gmolabeler/lib/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /usr/bin/cat
checking for local ICUDT_DIR... icu69/data
checking for x86_64-conda-linux-gnu-gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/michael/anaconda3/envs/gmolabeler/bin/x86_64-conda-linux-gnu-cpp
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... no
*** Trying with C++11 compiler disabled.
checking for local ICUDT_DIR... icu55/data
checking for x86_64-conda-linux-gnu-gcc... x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda-linux-gnu-cc accepts -g... yes
checking for x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /home/michael/anaconda3/envs/gmolabeler/bin/x86_64-conda-linux-gnu-cpp
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for elf.h... (cached) yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... no

*** *********************************************************************
*** stringi cannot be built with these settings in place.
*** See the INSTALL file for the solutions to the most common problems.
*** Moreover, explore the list of open and closed issues at
*** https://github.com/gagolews/stringi/issues/
*** *********************************************************************

ERROR: configuration failed for package ‘stringi’
* removing ‘/home/michael/anaconda3/envs/gmolabeler/lib/R/library/stringi’

The downloaded source packages are in
        ‘/tmp/Rtmpfy3QLD/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status
```
  
Thanks for your time and help! Please let me know if any details or tests on my end would be helpful to diagnose the issue.

**Comment by gagolews** [comment] 2021-11-07 22:57
Possible duplicate of #452 ?

**Comment by naglemi** [comment] 2021-11-09 23:04
Thank you gagolews. I've tried the steps described in #452 and am still having the issue. I've posted details in that issue thread.

**Comment by gagolews** [comment] 2021-11-09 23:33
Let's move the discussion there.

**Closed by gagolews** 2021-11-09 23:33 UTC
