### ISSUE TITLE
make: *** [icu69/common/uarrsort.o] Error 1

### ISSUE THREAD

**Issue by Dokmen** [gagolews/stringi#432] opened 2021-05-15 05:27 UTC
Hi all,

I have errors during installation of stringi package. I'm a user  in the linux-gnu with gcc 4.8.5 and my R version is 4.0.2. I do not have root privileges. The installation errors are:

 `install.packages("stringi")
Installing package into ?/truba/home/XXXX/R/x86_64-pc-linux-gnu-library/4.0?
(as ?lib? is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.6.1.tar.gz'
Content type 'application/x-gzip' length 7569954 bytes (7.2 MB)
downloaded 7.2 MB

* installing *source* package ?stringi? ...
** package ?stringi? successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /truba/sw/centos7.3/app/R/4.0.2/lib64/R
checking for R... /truba/sw/centos7.3/app/R/4.0.2/lib64/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu69/data
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /bin/pkg-config
checking with pkg-config for the system ICU4C... 50.2
checking for ICU4C >= 55... no
*** ICU4C 50.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 55, are not met
*** Trying with 'standard' fallback flags
checking whether an ICU4C-based project can be built... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** This version of ICU4C cannot be used.
checking whether we may compile src/icu69/common/putil.cpp... yes
checking whether we may compile src/icu69/i18n/number_affixutils.cpp... yes
checking whether the ICU data library can be downloaded... downloading the ICU data library (icudt)
output path: icu69/data/icu4c-69_1-data-bin-l.zip
trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip'
Content type 'application/zip' length 11454999 bytes (10.9 MB)
==================================================
downloaded 10.9 MB

icudt fetch successful
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/uconfig_local.h
config.status: creating src/install.libs.R

*** stringi configure summary:
    ICU_FOUND=0
    ICUDT_DIR=icu69/data
    ICU_BUNDLE_VERSION=69
    ICUDT_ENDIANNESS=little
    STRINGI_CXXSTD=CXX_STD=CXX11
    STRINGI_CFLAGS=   -fpic
    STRINGI_CPPFLAGS=-I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H
    STRINGI_CXXFLAGS=   -fpic
    STRINGI_LDFLAGS=  
    STRINGI_LIBS=  

*** Compiler settings used:
    CC=gcc -std=gnu99
    LD=g++ -std=gnu++11
    CFLAGS=-g -O2 -fpic  
    CPPFLAGS=-I/usr/local/include   -UDEBUG -DNDEBUG
    CXX=g++ -std=gnu++11
    CXXFLAGS=-g -O2 -fpic  
    LDFLAGS=  
    LIBS=  

** libs
g++ -std=gnu++11 -I"/truba/sw/centos7.3/app/R/4.0.2/lib64/R/include" -DNDEBUG -I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -fpic -fpic  -g -O2  -c stri_brkiter.cpp -o stri_brkiter.o
g++ -std=gnu++11 -I"/truba/sw/centos7.3/app/R/4.0.2/lib64/R/include" -DNDEBUG -I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -fpic -fpic  -g -O2  -c stri_collator.cpp -o stri_collator.o
g++ -std=gnu++11 -I"/truba/sw/centos7.3/app/R/4.0.2/lib64/R/include" -DNDEBUG -I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -fpic -fpic  -g -O2  -c stri_common.cpp -o stri_common.o
g++ -std=gnu++11 -I"/truba/sw/centos7.3/app/R/4.0.2/lib64/R/include" -DNDEBUG -I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -fpic -fpic  -g -O2  -c stri_compare.cpp -o stri_compare.o
g++ -std=gnu++11 -I"/truba/sw/centos7.3/app/R/4.0.2/lib64/R/include" -DNDEBUG -I. -Iicu69         -DU_STRINGI_PATCHES         -Iicu69/unicode -Iicu69/common         -Iicu69/i18n -DU_STATIC_IMPLEMENTATION         -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -I/usr/local/include  -fpic -fpic  -

--------------------------------------------
icu69/common/uarrsort.cpp: In function ?constexpr int32_t sizeInMaxAlignTs(int32_t)?:
icu69/common/uarrsort.cpp:40:34: error: ?max_align_t? is not a member of ?std?
     return (sizeInBytes + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t);
                                  ^
icu69/common/uarrsort.cpp:40:34: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:40:66: error: ?max_align_t? is not a member of ?std?
     return (sizeInBytes + sizeof(std::max_align_t) - 1) / sizeof(std::max_align_t);
                                                                  ^
icu69/common/uarrsort.cpp:40:66: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:41:1: error: body of constexpr function ?constexpr int32_t sizeInMaxAlignTs(int32_t)? not a return-statement
 }
 ^
icu69/common/uarrsort.cpp: In function ?void insertionSort(char*, int32_t, int32_t, int32_t (*)(const void*, const void*, const void*), const void*, UErrorCode*)?:
icu69/common/uarrsort.cpp:144:26: error: ?max_align_t? is not a member of ?std?
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                          ^
icu69/common/uarrsort.cpp:144:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:144:26: error: ?max_align_t? is not a member of ?std?
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                          ^
icu69/common/uarrsort.cpp:144:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:144:77: error: template argument 1 is invalid
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                             ^
icu69/common/uarrsort.cpp:144:76: error: ?constexpr int32_t sizeInMaxAlignTs(int32_t)? called in a constant expression
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                            ^
icu69/common/uarrsort.cpp:144:77: note: in template argument for type ?int? 
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                             ^
icu69/common/uarrsort.cpp:144:80: error: invalid type in declaration before ?;? token
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE)> v;
                                                                                ^
icu69/common/uarrsort.cpp:145:40: error: request for member ?getCapacity? in ?v?, which is of non-class type ?int?
     if (sizeInMaxAlignTs(itemSize) > v.getCapacity() &&
                                        ^
icu69/common/uarrsort.cpp:146:15: error: request for member ?resize? in ?v?, which is of non-class type ?int?
             v.resize(sizeInMaxAlignTs(itemSize)) == nullptr) {
               ^
icu69/common/uarrsort.cpp:151:62: error: request for member ?getAlias? in ?v?, which is of non-class type ?int?
     doInsertionSort(array, length, itemSize, cmp, context, v.getAlias());
                                                              ^
icu69/common/uarrsort.cpp: In function ?void quickSort(char*, int32_t, int32_t, int32_t (*)(const void*, const void*, const void*), const void*, UErrorCode*)?:
icu69/common/uarrsort.cpp:238:26: error: ?max_align_t? is not a member of ?std?
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                          ^
icu69/common/uarrsort.cpp:238:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:238:26: error: ?max_align_t? is not a member of ?std?
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                          ^
icu69/common/uarrsort.cpp:238:26: note: suggested alternative:
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from icu69/common/uarrsort.cpp:21:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h:425:3: note:   ?max_align_t?
 } max_align_t;
   ^
icu69/common/uarrsort.cpp:238:81: error: template argument 1 is invalid
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                 ^
icu69/common/uarrsort.cpp:238:76: error: ?constexpr int32_t sizeInMaxAlignTs(int32_t)? called in a constant expression
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                            ^
icu69/common/uarrsort.cpp:238:81: note: in template argument for type ?int? 
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                 ^
icu69/common/uarrsort.cpp:238:85: error: invalid type in declaration before ?;? token
     icu::MaybeStackArray<std::max_align_t, sizeInMaxAlignTs(STACK_ITEM_SIZE) * 2> xw;
                                                                                     ^
icu69/common/uarrsort.cpp:239:42: error: request for member ?getCapacity? in ?xw?, which is of non-class type ?int?
     if(sizeInMaxAlignTs(itemSize)*2 > xw.getCapacity() &&
                                          ^
icu69/common/uarrsort.cpp:240:16: error: request for member ?resize? in ?xw?, which is of non-class type ?int?
             xw.resize(sizeInMaxAlignTs(itemSize) * 2) == nullptr) {
                ^
icu69/common/uarrsort.cpp:246:21: error: request for member ?getAlias? in ?xw?, which is of non-class type ?int?
                  xw.getAlias(), xw.getAlias() + sizeInMaxAlignTs(itemSize));
                     ^
icu69/common/uarrsort.cpp:246:36: error: request for member ?getAlias? in ?xw?, which is of non-class type ?int?
                  xw.getAlias(), xw.getAlias() + sizeInMaxAlignTs(itemSize));
                                    ^
make: *** [icu69/common/uarrsort.o] Error 1
ERROR: compilation failed for package ?stringi?
* removing ?/truba/home/XXX/R/x86_64-pc-linux-gnu-library/4.0/stringi?
Warning in install.packages :
  installation of package ?stringi? had non-zero exit status

The downloaded source packages are in
	?/tmp/RtmpltHYYB/downloaded_packages?`

I can not understand what is happening.  I coul not find these errors on the google for fixing. Can you have any suggestion?

**Comment by gagolews** [comment] 2021-05-15 08:56
Duplicate of #431.

**Closed by gagolews** 2021-05-15 08:56 UTC
